# frozen_string_literal: true

# == Schema Information
#
# Table name: autores
#
#  id         :uuid             not null, primary key
#  foto       :string
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Autor < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :treinamentos, dependent: :destroy
  # validations ...............................................................
  validates :nome, :foto, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  mount_base64_uploader :foto, ImageUploader
  # class methods .............................................................
  # instance methods ..........................................................
end
