# frozen_string_literal: true

# == Schema Information
#
# Table name: categorias
#
#  id         :uuid             not null, primary key
#  titulo     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Categoria < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :treinamentos, dependent: :destroy

  # validations ...............................................................
  validates :titulo, presence: true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # instance methods ..........................................................
end
